### ISSUE TITLE
【バグ】プラグインが正常に削除されない。

### ISSUE THREAD

**Issue by pasmophobia** [TeamKun/TeamKUNPluginManager#20]
消したはずのプラグインが消えていない
![ShareX_vu9grK22Tk](https://user-images.githubusercontent.com/62823412/108584934-88a20c80-7388-11eb-8b70-e424422aea81.png)

**Comment by PeyaPeyaPeyang** [comment]
この動作は仕様で、依存関係になっているプラグインを先に削除することはできません...
依存関係元プラグインを先に削除して、そのあとに`/kpm autoremove`を実行していただきますようよろしくおねがいします。
