### ISSUE TITLE
【バグ】<spigotのURLからダウンロードできない>

### ISSUE THREAD

**Issue by pasmophobia** [TeamKun/TeamKUNPluginManager#29]
# 【バグ】<spigotのURLからダウンロードできない>

## 概要

/kpm install <spigotのダウンロードURL>
でプラグインを正常にインストールできない

## スクリーンショット
![javaw_Q9qcCAJVbF](https://user-images.githubusercontent.com/62823412/108977298-be6a2c80-76cb-11eb-9c69-eec11772abad.png)
![javaw_qnxfX0xpNG](https://user-images.githubusercontent.com/62823412/108977292-bca06900-76cb-11eb-804e-449bbeea64aa.png)

**Comment by PeyaPeyaPeyang** [comment]
SpigotのURLには、CloudFlareを用いた分散処理とリダイレクトがあるため、正常に機能できません><
APIを用いたjarの直接取得をFeatureとして立てておきます。
