### ISSUE TITLE
表示された文字が誤っている・GitHubサーバーのトークン生成時に問題が発生する

### ISSUE THREAD

**Issue by Taro-Kenchiku** [TeamKun/TeamKUNPluginManager#92]
GitHubサーバーを用いてトークンを生成しますか？**y/N>**←<が抜けている
その後 y を打とうとしたら Unknown　Command. Type "/help" for help.
と表示される問題が発生する

**Comment by PeyaPeyaPeyang** [comment]
Issueありがとうございます.
お手数ですが, [正しいフォーマット](https://github.com/TeamKun/TeamKUNPluginManager/issues/new?assignees=peyang-Celeron&labels=Type%3A+Bug&template=bug_report.yml&title=%E3%80%90%E3%83%90%E3%82%B0%E3%80%91)で新しくIssueを作成してください.
